//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jamiaAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user
    {
        public int userID { get; set; }
        public string userDisplayName { get; set; }
        public string userName { get; set; }
        public string userPassword { get; set; }
        public string userCellNumber { get; set; }
        public int CID { get; set; }
        public int BID { get; set; }
        public string userRole { get; set; }
        public string userToken { get; set; }
    
        public virtual tbl_batch tbl_batch { get; set; }
        public virtual tbl_campus tbl_campus { get; set; }
    }
}
