//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jamiaAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_course()
        {
            this.tbl_files = new HashSet<tbl_files>();
            this.tbl_batch = new HashSet<tbl_batch>();
        }
    
        public int courseID { get; set; }
        public string courseName { get; set; }
        public string courseInstructor { get; set; }
        public string courseDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_files> tbl_files { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_batch> tbl_batch { get; set; }
    }
}
