//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jamiaAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_files
    {
        public int fileID { get; set; }
        public string fileDispName { get; set; }
        public string filePath { get; set; }
        public string fileType { get; set; }
        public string fileDescription { get; set; }
        public int fileCourse { get; set; }
    
        public virtual tbl_course tbl_course { get; set; }
    }
}
