//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jamiaAPP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JamiaRDBEntities : DbContext
    {
        public JamiaRDBEntities()
            : base("name=JamiaRDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_batch> tbl_batch { get; set; }
        public virtual DbSet<tbl_campus> tbl_campus { get; set; }
        public virtual DbSet<tbl_course> tbl_course { get; set; }
        public virtual DbSet<tbl_files> tbl_files { get; set; }
        public virtual DbSet<tbl_user> tbl_user { get; set; }
    }
}
